version: '3'

services:
  ktb.server:
    container_name: ktb.server
    build:
      context: ./docker/
      dockerfile: Dockerfile-server
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./docker-data-server:/var/www/data
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APP_SECRET=${APP_SECRET:-secret}
      - DB_HOST=${MYSQL_HOST:-ktb.db}
      - DB_PORT=${MYSQL_PORT:-3306}
      - DB_NAME=${MYSQL_DATABASE:-ktb}
      - DB_USER=${MYSQL_USER:-ktb}
      - DB_PASSWORD=${MYSQL_PASSWORD:-ktb}

  ktb.db:
    container_name: ktb.db
    image: mariadb:10.11.4-jammy
    volumes:
      - ./docker-data-mysql:/var/lib/mysql
    security_opt:
      - 'seccomp=unconfined'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-ktb}
      - MYSQL_USER=${MYSQL_USER:-ktb}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-ktb}